{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-mcp.fullname" . }}-secret
  labels:
    {{- include "cloud-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
